name: CI Pipeline

# Trigger on pull requests and pushes to the main branch.
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  # this job is for building the image, running tests and scanning for vulnerabilities.
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build the Docker image.
      - name: Build Docker image
        run: docker build -t myflaskapp .

      # Run tests.
      - name: Run tests
        run: echo "Test_v1"

###
      # Moved the Trivy scan to a separate continuous compliance pipeline 

      # # This step scans the Docker image for vulnerabilities using a tool called Trivy.
      # - name: Scan Docker image with Trivy
      #   run: |
      #     docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
      #       aquasecurity/trivy:latest myflaskapp || true
      #   # Added "|| true" to the end of docker run command to allow warnings without failing the build
###

  # Deploy job runs only on pushes (merges) to main.
  deploy:
    #if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3

      # Rebuild the Docker image (we could also use artifacts, so we can avoid the redundancy of building this image twice)
      - name: Build Docker image
        run: docker build -t myflaskapp .

      # Run some more tests before deployment.
      - name: Run tests
        run: echo "Test_v2"

      # Push the Docker image to GitHub Container Registry (it will push both a tagged version as well as the latest version).
      - name: Push to GitHub Registry with Versioning
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # Tag the image with both the commit SHA and "latest"
          docker tag myflaskapp ghcr.io/${{ github.repository }}/myflaskapp:${IMAGE_TAG}
          docker tag myflaskapp ghcr.io/${{ github.repository }}/myflaskapp:latest
          # Push both tags
          docker push ghcr.io/${{ github.repository }}/myflaskapp:${IMAGE_TAG}
          docker push ghcr.io/${{ github.repository }}/myflaskapp:latest